
' actor "usuario" as u
' participant "sistema" as s  
' database "base de datos" as bd

' u -> s:iniciarSesion(correo,contraseña)
' activate s

' u->s:solicita las sanciones del usuario
' s->s:verUsuario(idUsuario)
' activate s
' deactivate s
' s->s: analiza las sanciones y resume todas las sanciones
' group si tienne sanciones
'     s->u: muestra las sanciones en una ventana
' else
'     s->u: muestra que no tiene sanciones
' end
' s->s:ciera la ventana de sanciones



@startuml
participant ":registro" as u
database "base de datos" as bd

->u:detectar_sansion(is_usuario)
activate u
u->bd:detectar_sanciones(id_prestamo)
group if
    note over bd: detectar_sanciones devuelve true
    u->u:msj("Sansion activa")

else
    note over bd: detectar_sanciones devuelve false
    u->u:msj("No tiene sanciones")

end
deactivate u


@enduml