@startuml
title caso de uso: eliminar sancion
participant ":administrador" as u
database "base de datos" as db

-> u:eliminar_sancion(id_usuario)
create "prestamo" as p
u -> p:create()
create "sanccion" as s
p -> s:create()
s-> db:update_sancion(fechar_fin)


@enduml


