@startuml
title caso de uso: listar lectores sancionados
actor ":abministrador" as a
 

-> a: listar_lectores_sancionados()
activate a
a->db:get_lectores_sancionados()
  create ":usuario" as u
  db->u: create()
a<<--u:list:usuario
database "base de datos" as db 

activate db
deactivate db

deactivate a

@enduml
' u -> s:iniciarSesion(correo,contraseña)
' activate s
' u -> s:el usuario presiona boton de ver lectores sancionados
' u -> s:LisarLectoresSacionados()
' activate s
' s -> db:select * from lectores where sancionado = true
' activate db
' deactivate db
' group hay lectores sancionados
' s -> s:retornar lista de lectores sancionados
' note right of u
'  se muestra en la interfaz grafica e puede
' desplazarse usando el scroll del mouse

' end note
' else no hay lectores sancionados
' s -> s:retornar mensaje de que no hay lectores sancionados
' s->s: cerrar mensaje despues de 5 segundos
' end
' deactivate s


