@startuml

actor ":abministrador" as u
database "base de datos" as db  

-> u: listar_lectores_sancionados()
activate u
u->db:get_lectores_sancionados()
activate db
deactivate db


deactivate u


' u -> s:iniciarSesion(correo,contraseña)
' activate s
' u -> s:el usuario presiona boton de ver lectores sancionados
' u -> s:LisarLectoresSacionados()
' activate s
' s -> db:select * from lectores where sancionado = true
' activate db
' deactivate db
' group hay lectores sancionados
' s -> s:retornar lista de lectores sancionados
' note right of u
'  se muestra en la interfaz grafica e puede
' desplazarse usando el scroll del mouse

' end note
' else no hay lectores sancionados
' s -> s:retornar mensaje de que no hay lectores sancionados
' s->s: cerrar mensaje despues de 5 segundos
' end
' deactivate s


@enduml