@startuml
title Listar sancion

actor "Bibliotecario, Administrador" as Administrador
participant Sistema
database BaseDatos

Administrador->Sistema: Solicitar listar sanciones
Sistema->BaseDatos: Consultar usuarios sancionados
group Usuarios sancionados encontrados
    note over Sistema: Usuarios sancionados encontrados
    Sistema->Administrador: Mostrar lista de usuarios sancionados
    Administrador->Sistema: (Opcional) Seleccionar usuario
    Sistema->BaseDatos: Obtener detalles de la sanción del usuario
    BaseDatos->Sistema: Devolver detalles de la sanción
    Sistema->Administrador: Mostrar detalles de la sanción del usuario
else No hay usuarios sancionados
    note over Sistema: No hay usuarios sancionados
    Sistema->Administrador: Mostrar mensaje("No hay usuarios sancionados")
end
@enduml
