@startuml
' title caso de uso: listar usuarios
'  actor "Administrador" as u
' participant "sistema" as s
' database "Base de datos" as DB
' -->>s: Sesioniniciada()
' activate s
' -->>s: listarUsuarios()
' activate s
' u->>s: El usuario da click en el menu de la aplicacion
' u->>s: El usuario da click en la opcion usuarios

' s->>DB: SELECT * FROM usuarios
' activate DB
' DB->>s: Lista de usuarios
' deactivate DB
' s->>u: El sistema abre ventana y despliega la lista de usuarios

'     note right of u: El administrador navegar usando la scrull del mouse

' deactivate s
title Caso de uso: Listar Usuarios

actor ":Administrador" as a
database ":BaseDeDatos" as bd
participant ":Usuario" as u

-> a:listar_usuarios()
activate a

a -> bd:get_usuarios()
activate bd

bd --> a:datosUsuarios
deactivate bd

create ":Usuario" as usuario
a -> usuario:create(datosUsuarios)
activate usuario

usuario-->>a::usuario
deactivate usuario

deactivate a

@enduml
