@startuml
title caso de uso: ver informacion de usuario
actor "Usuario" as U
participant "sistema" as S
database "Base de datos" as BD
-->>S: SesionIniciada()
activate S
-->>S: VerInformacionUsuario()
activate S
U->S: presiona el boton de de ver informacion


S->BD: consulta la informacion
activate BD
BD->S: devuelve la informacion
deactivate BD
S->U: muestra la informacion en pantalla
U->S: presiona el boton de aceptar
S->S:cierra la ventana
deactivate S





@enduml